# SPDX-FileCopyrightText: 2023 LakeSoul Contributors
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "lakesoul-io"
version = "2.5.0"
edition = "2021"

[dependencies]
datafusion = { workspace = true }
object_store = { workspace = true }

tokio-stream =  {workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
derivative = { workspace = true }
atomic_refcell = { workspace = true }
arrow = { workspace = true, features = ["prettyprint"]}
arrow-schema = { workspace = true, features = ["serde"] }
arrow-array = { workspace = true, features = ["chrono-tz"] }
arrow-buffer = { workspace = true }
parquet = { workspace = true, features = ["async", "arrow"] }
futures = { workspace = true }
datafusion-common = { workspace = true }
serde = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
smallvec = "1.10"
dary_heap = "0.3"
bytes = { workspace = true }
hdrs = { git = "https://github.com/lakesoul-io/hdrs.git", branch = "main", features = ["async_file"], optional = true }
lazy_static = "1.4.0"
chrono = "0.4"
serde_json = { workspace = true }
log = { workspace = true }
proto = { path = "../proto" }
parking_lot = "0.12.1"

half = { workspace = true }


[features]
hdfs = ["dep:hdrs"]
simd = ["datafusion/simd", "arrow/simd", "arrow-array/simd"]
default = []

[dev-dependencies]
tempfile = "3.3.0"
comfy-table = "6.0"
whoami = "1.3"
rand = "0.8"
