#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'

services:
  postgres:
    image: postgres:14.5
    container_name: lakesoul-ann-pg
    hostname: ${LAKESOUL_META_HOST}
    networks:
      - lakesoul-ann
    ports:
      - "${PG_PORT}:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: lakesoul_test
      POSTGRES_USER: lakesoul_test
      POSTGRES_DB: lakesoul_test
    command:
      - "postgres"
      - "-c"
      - "max_connections=4096"
      - "-c"
      - "default_transaction_isolation=serializable"
    volumes:
      - ./sql/meta_init.sql:/docker-entrypoint-initdb.d/meta_init.sql
      - ./sql/meta_cleanup.sql:/meta_cleanup.sql

  minio:
    image: swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/bitnami/minio:2025.4.22-debian-12-r1
    container_name: lakesoul-ann-minio
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_UI_PORT}:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    hostname: minio
    networks:
      - lakesoul-ann
    command: /opt/bitnami/minio/bin/minio server /data --console-address ":9001"

  spark:
    image: swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/bitnami/spark:3.3.1
    container_name: lakesoul-ann-spark
    privileged: true
    user: root
    volumes:
      - ./packages/jars/lakesoul-spark-3.3-2.6.2-SNAPSHOT.jar:/opt/bitnami/spark/jars/lakesoul-spark-3.3-2.6.2-SNAPSHOT.jar
      # - ./packages/jars/lakesoul-spark-3.3-2.6.2-SNAPSHOT-tests.jar:/opt/bitnami/spark/jars/lakesoul-spark-3.3-2.6.2-SNAPSHOT-tests.jar
      - ./data/spark-conf:/opt/bitnami/spark/conf
      - ./sql/prepare_ann_benchmark.sql:/opt/sql/prepare_ann_benchmark.sql
      - ./data/embeddings:/data/embeddings
      - ./python:/opt/bitnami/spark/python
    depends_on:
      - postgres
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - LAKESOUL_PG_DRIVER=com.lakesoul.shaded.org.postgresql.Driver
      - LAKESOUL_PG_URL=jdbc:postgresql://${LAKESOUL_META_HOST}:5432/lakesoul_test?stringtype=unspecified
      - LAKESOUL_PG_USERNAME=lakesoul_test
      - LAKESOUL_PG_PASSWORD=lakesoul_test
    networks:
      - lakesoul-ann

networks:
  lakesoul-ann:
    ipam:
      driver: default